apiVersion: v1
kind: Pod
metadata:
  name: limit-range-default
  namespace: quota-test
spec:
  containers:
    - name: busybox
      image: 192.168.190.140:5000/library/busybox:1.26
      command: ["sleep", "3600"]
