apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1gi-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nfsroot/v1
    server: 192.168.190.140
