apiVersion: v1
kind: Service
metadata:
  name: statefulset-test
  labels:
    app: statefulset-test
    date: "0314"
spec:
  selector:
    app: statefulset-test
  type: ClusterIP
  clusterIP: None
  ports:
    - name: web
      port: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-test
  labels:
    app: statefulset-test
    date: "0314"
spec:
  serviceName: "statefulset-test"
  replicas: 2
  selector:
    matchLabels:
      app: statefulset-test
      date: "0314"
  template:
    metadata:
      name: statefulset-test
      labels:
        app: statefulset-test
        date: "0314"
    spec:
      containers:
        - name: nginx
          image: 192.168.190.140:5000/library/nginx:1.17.9
          ports:
            - name: web
              containerPort: 80
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi


