apiVersion: v1
kind: Pod
metadata:
  name: podpreset-test
  namespace: default
  labels:
    tz: shanghai
spec:
  containers:
    - name: busybox
      image: 192.168.190.140:5000/library/busybox:1.26
      command: ["sleep", "3600"]
