apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-5gi
  namespace: kube-system
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /nfsroot/v4
    server: 192.168.190.140

