apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-grafana-5gi
  namespace: kube-system
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /nfsroot/v5
    server: 192.168.190.140

