apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv2
  namespace: default
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /local-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
           - key: kubernetes.io/hostname
             operator: In
             values:
               - k8s-node-1
