apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox
  name: mybusybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - image: 192.168.190.140:5000/library/busybox:1.26
        name: mybusybox
        command: ["sleep", "3600"]
